<?php
/** @var $block \SmartOSC\Blog\Block\Post\PostList */ ?>
<?php $helper = $block->getHelperData() ?>


    <?php /** @var $post \SmartOSC\Blog\Api\Data\PostInterface */ ?>
        <?php foreach ($block->getNews() as $post): ?>
        <?php if($block->isAsigned($post->getCategoryIds())):?>
        <div class="blog-post-item">
            <div class="blog-post-item-content">
                <div class="blog-post-item-image">
                    <a href="<?php echo $block->getPostUrl($post->getPostId()); ?>">
                        <img src="<?php echo $block->getMediaUrl().$post->getImage(); ?>" />
                    </a>
                </div>
                <div class="blog-post-item-data">
                    <h3 class="blog-post-item-title" style="margin:10px 0 10px 0;">
                        <strong><a href="<?php echo $block->getPostUrl($post->getPostId()); ?>"><?php echo $post->getTitle() ?></a></strong>
                    </h3>
                    <div>
                        <p><?php echo $helper->timeElapsed($post->getCreatedAt()) ?></p>
                    </div>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <?php endforeach; ?>

<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>