<?php
/** @var $block \SmartOSC\Blog\Block\Post\View */
$post = $block->getPost();
if($post != null):
?>
<div class="post-view">
    <div class="post-view-header">
        <h1 class="post-view-header-title"><?php echo $post->getTitle() ?></h1>
        <p class="post-view-header-date"><?php echo date('F j, Y', strtotime($post->getCreatedAt())) ?></p>
    </div>
    <div class="post-view-featured-image">
        <img src="<?php echo $block->getMediaUrl().$post->getImage(); ?>" />
    </div>
    <div class="post-view-content">
        <?php echo $post->getContent(); ?>
    </div>

    <div class="blog_product_post_list">
        <h2>Product Related</h2>
        <ul class="blog_product_post_list" style="padding: 0 0 0 0;">
            <?php foreach ($block->getProductIds() as $productId):?>
            <?php if($productId != ''):
                    $product = $block->getProductById($productId);
                    $imgUrl = $this->getItemImage($productId);?>
            <li class="block-product-posts-item">
                <a href="<?php echo $product->getProductUrl() ?>">
                    <img class="product-post-featured-image"
                         src="<?php echo $imgUrl; ?>"
                </a><br>
                <a href="<?php echo $product->getProductUrl() ?>"><?php echo $product->getName() ?></a>
            </li>
            <?php endif;?>
            <?php endforeach;?>
        </ul>
    </div>
</div>
<?php endif; ?>


